// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.blurt.collector {
    exports com.mastfrog.blurt.collector;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;

    // Sibling com.mastfrog/acteur-mongo-3.0.0-dev
    requires com.mastfrog.acteur.mongo;

    // Sibling com.mastfrog/Blurt-3.0.0-dev
    requires com.mastfrog.blurt;

    // Transitive detected by source scan
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/jackson-3.0.0-dev
    requires com.mastfrog.jackson;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.preconditions;
    provides com.mastfrog.jackson.JacksonConfigurer with
       com.mastfrog.blurt.collector.JacksonMongoIDConfig;

}
