open module com.mastfrog.blurt.collector {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.blurt.collector;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.acteur.mongo;
    requires transitive com.mastfrog.blurt;
    requires transitive com.mastfrog.jackson;

}
